Check docker executable existence

diff --git a/bin/lproxy-purge b/bin/lproxy-purge
--- a/bin/lproxy-purge
+++ b/bin/lproxy-purge
@@ -1,9 +1,17 @@
 #/bin/sh
 
+DKVER=`docker -v 2>/dev/null|awk '{print $3}'`
+if [ "$DKVER" = "" ]; then
+	echo "Docker executable not found."
+	echo "Abort."
+	exit 255
+fi
+
 BEXIST=`docker ps -a| grep ssllibev|wc -l`
 if [ $BEXIST -gt 0 ]; then
 	echo "Local proxy found. Purging..."
-	docker stop ssllibev; docker rm ssllibev
+	docker stop ssllibev >/dev/null
+	docker rm ssllibev >/dev/null
 	echo
 	echo "Done."
 else
diff --git a/bin/lproxy-status b/bin/lproxy-status
--- a/bin/lproxy-status
+++ b/bin/lproxy-status
@@ -1,5 +1,12 @@
 #/bin/bash
 
+DKVER=`docker -v 2>/dev/null|awk '{print $3}'`
+if [ "$DKVER" = "" ]; then
+	echo "Docker executable not found."
+	echo "Abort."
+	exit 255
+fi
+
 BEXIST=`docker ps| grep ssllibev|wc -l`
 if [ $BEXIST -eq 0 ]; then
 	echo "Local proxy is not running."
diff --git a/vlp b/vlp
--- a/vlp
+++ b/vlp
@@ -14,15 +14,22 @@ IMGNAME="samuelhbne/vpnlaunchpad"
 IMGVER="$ARCH.$DKUID.$DKGID"
 IMGTAG="$IMGNAME:$IMGVER"
 
-BIMG=`docker images |grep $IMGNAME|grep -c $IMGVER`
+DKVER=`docker -v 2>/dev/null|awk '{print $3}'`
+if [ "$DKVER" = "" ]; then
+	echo "Docker executable not found.."
+	echo "Abort."
+	exit 255
+fi
+
+#BIMG=`docker images |grep $IMGNAME|grep -c $IMGVER`
 #TDKFILE=`date +%Y%m%d%H%M%S -r $VLPDKDIR/Dockerfile.in`
 #TIMG=`docker inspect -f '{{ .Created }}' $IMGTAG 2>/dev/null`
 #TIMG=`date --date "$TIMG" +%Y%m%d%H%M%S`
 
-if [ "$BIMG" = "0" ]; then
-	echo "Image $IMGNAME not found."
-	BUILD=1
-fi
+#if [ "$BIMG" = "0" ]; then
+#	echo "Image $IMGNAME not found."
+#	BUILD=1
+#fi
 
 #if [ "$TDKFILE" -gt "$TIMG" ]; then
 #	echo "Updated upstream detected: $VLPDKDIR/Dockerfile.in"
