Execute host based ssh instead of container based ssh.

diff --git a/bin/vlp-ssh b/bin/vlp-ssh
--- a/bin/vlp-ssh
+++ b/bin/vlp-ssh
@@ -19,19 +19,16 @@ IPADDR=`echo $RESULT|awk '{print $1}'`
 INSTID=`echo $RESULT|awk '{print $2}'`
 
 echo
-if [ ! -z "$IPADDR" ]; then
-	echo "VPN-SERVER: $IPADDR $INSTID"
-else
-	echo "VPN-SERVER: None"
-	exit 1
+if [ -z "$IPADDR" ]; then
+	echo "VPN Server not found."
+	exit 2
 fi
-echo
 
 if [ -f $VLPKEY ]; then
-	echo "SSH private key found. ssh to $IPADDR..."
-	echo
-	ssh -i $VLPKEY ubuntu@$IPADDR "$@"
+	echo -e "VPSKEY=$STACKID.$REGION.pem\nVPSADDR=$IPADDR" > $VLPCFG/ssh.env
+	exit 0
 else
-	echo "SSH private key not found. Not created from this box?"
+	echo "SSH private key $STACKID.$REGION.pem not found. Not created from this box?"
+	exit 1
 fi
 exit 0
diff --git a/vlp b/vlp
--- a/vlp
+++ b/vlp
@@ -103,15 +103,21 @@ while [[ $# > 0 ]]; do
 			;;
 		ssh)
 			shift
-			if ls $VLPKEY 1> /dev/null 2>&1; then
-				echo "Private key found: `ls $VLPKEY`"
-				$DOCKERCMD /vlp/bin/vlp-ssh "$@"
-				exit $?
+			$DOCKERCMD /vlp/bin/vlp-ssh
+			RETCODE="$?"
+			if [ $RETCODE = "0" ]; then
+				. $VLPCFG/ssh.env
+				if [ "$VPSKEY" != "" ] || [ "$VPSADDR" != "" ]; then
+					echo "ssh -i $VLPCFG/$VPSKEY ubuntu@$VPSADDR \"$*\""
+					echo
+					ssh -i $VLPCFG/$VPSKEY ubuntu@$VPSADDR "$*"
+					exit 0
+				else
+					echo "Failed reading ssh env. Read only folder?"
+					exit 254
+				fi
 			else
-				echo "Private key not found"
-				echo "Not created from this box?"
-				echo "Abort."
-				exit 255
+				exit $RETCODE
 			fi
 			;;
 		*)
